import type { Metadata } from "next";
import { Jura } from "next/font/google";
import Hyrax from "next/font/local";
import "./globals.css";
import "./color.css";
import "./font.css";
import "./section.css";
import "./button.css";
import NavBar from "@/comps/NavBar";
import Footer from "@/comps/Footer";

const jura = Jura({
  variable: "--font-jura",
  weight: "variable",
  subsets: ["latin"],
});

const hyrax = Hyrax({
  src: "../fonts/hyrax.woff",
  variable: "--font-hyrax",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jura.variable} ${hyrax.variable}`}>
      <body>
        <NavBar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
